services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 1880:1880
    volumes:
      - nodered-data:/data
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: always

volumes:
  nodered-data:
  portainer-data:

networks:
  haberdashery-warp:
